import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  type LucideIcon,
  // Ícones adicionais para dashboard
  BarChart,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Calendar,
  Clock,
  Users,
  ShoppingBag,
  ShoppingCart,
  Package,
  Award,
  Zap,
  Eye,
  MousePointer,
  RefreshCw,
  MoreHorizontal,
  Lightbulb,
  Trophy,
  GraduationCap,
  Download,
  Bell,
  Menu,
  ChevronDown,
  ChevronUp,
  Upload,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: User,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  check: Check,
  warning: AlertTriangle,
  addCircle: Plus,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  fileText: FileText,
  arrowRight: ArrowRight,
  file: File,
  image: Image,
  
  // Dashboard icons
  dashboard: BarChart,
  institute: GraduationCap,
  ecommerce: ShoppingBag,
  tables: FileText,
  upload: Upload,
  chart: LineChart,
  barChart: BarChart,
  pieChart: PieChart,
  lineChart: LineChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  money: DollarSign, 
  dollarSign: DollarSign,
  calendar: Calendar,
  time: Clock,
  users: Users,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart, 
  package: Package,
  award: Award,
  zap: Zap,
  eye: Eye,
  mousePointer: MousePointer,
  refresh: RefreshCw,
  moreHorizontal: MoreHorizontal,
  lightbulb: Lightbulb,
  trophy: Trophy,
  graduationCap: GraduationCap,
  download: Download,
  notifications: Bell,
  menu: Menu,
  sidebarOpen: ChevronRight,
  sidebarClose: ChevronLeft,
};
