import {
  ArrowDown,
  ArrowUp,
  BarChart3,
  BookOpenText,
  Calendar,
  Coffee,
  Download,
  Filter,
  Home,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  RefreshCw,
  SearchIcon,
  ShoppingBag,
  Sun,
  Table,
  UploadCloud,
  User,
  X,
  CreditCard,
  LineChart,
  ArrowDownUp,
  PercentIcon,
  DollarSign,
  Loader2,
  Check
} from "lucide-react";

export const Icons = {
  logo: Coffee,
  sun: Sun,
  moon: Moon,
  close: X,
  spinner: Loader2,
  chevronLeft: ArrowDown,
  chevronRight: ArrowUp,
  check: Check,
  dashboard: Home,
  institute: BookOpenText,
  ecommerce: ShoppingBag,
  tables: Table,
  upload: UploadCloud,
  download: Download,
  refresh: RefreshCw,
  filter: Filter,
  calendar: Calendar,
  search: SearchIcon,
  user: User,
  sidebarOpen: PanelLeftOpen,
  sidebarClose: PanelLeftClose,
  chart: BarChart3,
  lineChart: LineChart,
  card: CreditCard,
  sort: ArrowDownUp,
  percentage: PercentIcon,
  money: DollarSign,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
};
